---

- name: check python presence
  raw: "python --version"
  register: try_python_command
  changed_when: false
  failed_when: false

- name: establish python
  when: try_python_command.rc != 0
  include_tasks: install_python.yml

- name: gather facts
  become: false
  setup: {}

- name: bootstrap system
  when: bootstrap_system
  include_tasks: bootstrap_system.yml
